### ISSUE TITLE
"undefined is not a function" while adding contact details for a new user

### ISSUE THREAD

**Issue by always-akshat** [airpair/consult.airpair.com#64]
While creating a profile, browser shows the following error.

    app-dc5e4ac918.js:3 TypeError: undefined is not a function
    at Object.<anonymous> (https://consult.airpair.com/js/app-dc5e4ac918.js:10:13065)
    at Object.i [as invoke] (https://consult.airpair.com/js/app-dc5e4ac918.js:1:29486)
    at Object.$get (https://consult.airpair.com/js/app-dc5e4ac918.js:1:27876)
    at Object.i [as invoke] (https://consult.airpair.com/js/app-dc5e4ac918.js:1:29486)
    at https://consult.airpair.com/js/app-dc5e4ac918.js:1:30063
    at r (https://consult.airpair.com/js/app-dc5e4ac918.js:1:29116)
    at Object.i [as invoke] (https://consult.airpair.com/js/app-dc5e4ac918.js:1:29453)
    at Object.$get (https://consult.airpair.com/js/app-dc5e4ac918.js:1:27876)
    at Object.i [as invoke] (https://consult.airpair.com/js/app-dc5e4ac918.js:1:29486)
    at https://consult.airpair.com/js/app-dc5e4ac918.js:1:30063 <main ng-view="" class="ng-scope">

**Comment by jkresner** [comment]
Thank you for posting - will be followed up. What version of the browser are you using so we can research

**Comment by jkresner** [comment]
To confirm this is the same as :+1: 

https://twitter.com/hrishio/status/687281829385256960

**Comment by always-akshat** [comment]
Thanks for the prompt reply.

system details :
ubuntu 14.04 LTS
Chrome Version 41.0.2272.118 (64-bit)

**Comment by nthj** [comment]
OS X Yosemite
Chrome 43.0.2357.132 (64-bit)

**Comment by nthj** [comment]
Confirmed same result on Firefox 33.1.1:

```"Error: Object.assign is not a function
[11]</<@https://consult.airpair.com/js/app-dc5e4ac918.js:10:13058
i@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29484
o/<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:27874
i@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29484
Ze/_.$injector<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:30061
r@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29116
i@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29453
o/<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:27874
i@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29484
Ze/_.$injector<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:30061
r@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29116
kn/this.$get</<@https://consult.airpair.com/js/app-dc5e4ac918.js:3:24119
Jt@https://consult.airpair.com/js/app-dc5e4ac918.js:3:2703
Zt@https://consult.airpair.com/js/app-dc5e4ac918.js:3:3743
Zt/<@https://consult.airpair.com/js/app-dc5e4ac918.js:3:2809
a@https://consult.airpair.com/js/app-dc5e4ac918.js:1:10931
Zt@https://consult.airpair.com/js/app-dc5e4ac918.js:3:2788
[8]</</an.prototype.compile@https://consult.airpair.com/js/app-dc5e4ac918.js:4:27723
[8]</</Qi.prototype.parse@https://consult.airpair.com/js/app-dc5e4ac918.js:5:9088
cn/this.$get</<@https://consult.airpair.com/js/app-dc5e4ac918.js:3:6924
u@https://consult.airpair.com/js/app-dc5e4ac918.js:2:26848
J@https://consult.airpair.com/js/app-dc5e4ac918.js:2:13617
z@https://consult.airpair.com/js/app-dc5e4ac918.js:2:7054
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5707
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
D@https://consult.airpair.com/js/app-dc5e4ac918.js:2:4631
L@https://consult.airpair.com/js/app-dc5e4ac918.js:2:10314
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5743
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5874
D@https://consult.airpair.com/js/app-dc5e4ac918.js:2:4631
L@https://consult.airpair.com/js/app-dc5e4ac918.js:2:10314
N@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5743
D@https://consult.airpair.com/js/app-dc5e4ac918.js:2:4631
o/<.link@https://consult.airpair.com/js/app-dc5e4ac918.js:1:9653
ie@https://consult.airpair.com/js/app-dc5e4ac918.js:2:15513
g@https://consult.airpair.com/js/app-dc5e4ac918.js:2:9496
s@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5605
D/<@https://consult.airpair.com/js/app-dc5e4ac918.js:2:5046
P/r@https://consult.airpair.com/js/app-dc5e4ac918.js:2:6100
c@https://consult.airpair.com/js/app-dc5e4ac918.js:2:8646
l@https://consult.airpair.com/js/app-dc5e4ac918.js:1:9286
hn/this.$get</d.prototype.$broadcast@https://consult.airpair.com/js/app-dc5e4ac918.js:3:16642
d/<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:8008
u@https://consult.airpair.com/js/app-dc5e4ac918.js:3:7679
c/<@https://consult.airpair.com/js/app-dc5e4ac918.js:3:7851
hn/this.$get</d.prototype.$eval@https://consult.airpair.com/js/app-dc5e4ac918.js:3:15267
hn/this.$get</d.prototype.$digest@https://consult.airpair.com/js/app-dc5e4ac918.js:3:13694
hn/this.$get</d.prototype.$apply@https://consult.airpair.com/js/app-dc5e4ac918.js:3:15549
oe/s/<@https://consult.airpair.com/js/app-dc5e4ac918.js:1:17672
i@https://consult.airpair.com/js/app-dc5e4ac918.js:1:29484
oe/s@https://consult.airpair.com/js/app-dc5e4ac918.js:1:17593
oe@https://consult.airpair.com/js/app-dc5e4ac918.js:1:17879
ae@https://consult.airpair.com/js/app-dc5e4ac918.js:1:17127
[8]</</<@https://consult.airpair.com/js/app-dc5e4ac918.js:6:4571
r@https://consult.airpair.com/js/app-dc5e4ac918.js:4:8149
Ve/n@https://consult.airpair.com/js/app-dc5e4ac918.js:1:26494
" "<main class="ng-scope" ng-view="">"```
